# Generated by Django 5.0 on 2024-02-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210830_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='username',
            new_name='uname',
        ),
    ]
